site_name: "pycodetags"
site_url: "https://pycodetags.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of pycodetags, a tool for TODO comments in source code"

repo_url: "https://github.com/matthewdeanmartin/pycodetags"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - "Overview": "index.md"
  - "Installation": "installation.md"
  - "Usage":
      - "Usage": "usage.md"
  - "Data Tags": "data_tags.md"
  # - "API": "api.md"
  - "Plugins":
      - "Issue Tracker": "plugin_issue_tracker.md"
      - "Discussion": "plugin_discussion.md"
      - "Code Review": "plugin_code_review.md"
      - "Plugin Directory": "plugin_list.md"
      - "Making a plugin": "plugin_how_to.md"
  - "FAQ": "FAQ.md"
  - "Prior Art": "PRIOR_ART.md"
  - "Changes": "CHANGELOG.md"
  - "Glossary": "Glossary.md"
  - "Contributing": "CONTRIBUTING.md"

validation:
  nav:
    omitted_files: warn