site_name: "pycodetags"
site_url: "https://pycodetags.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of pycodetags, a tool for TODO comments in source code"

repo_url: "https://github.com/matthewdeanmartin/pycodetags"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - "Overview": "index.md"
  - "Installation": "installation.md"
  - "Getting Started": "getting_started.md"
  - "Usage":
      - "Usage": "usage.md"
  - "Data Tags":
      - "Overview": "data_tags.md"
      - "Universal Plugin" : "plugins/plugin_universal.md"
      - "Sqlite Plugin" : "plugins/plugin_sqlite.md"

  - "Plugins for Software Development":
    - "Issue Tracker Plugin": "plugins/plugin_issue_tracker.md"
    - "Discussion Plugin": "plugins/plugin_discussion.md"
    - "Code Review Plugin": "plugins/plugin_code_review.md"
  - "Plugins":
      - "Plugin Directory": "plugins/plugin_list.md"
      - "Making a plugin": "plugins/plugin_how_to.md"
  - "API": "API.md"
  - "Design":
      - "001 Initializers" : "peps/PYTAGS_PEP_001_initializers.md"
      - "002 Performance" : "peps/PYTAGS_PEP_002_performance.md"
      - "003 Plugins" : "peps/PYTAGS_PEP_003_plugins.md"
      - "004 Catdogs" :  "peps/PYTAGS_PEP_004_catdogs.md"
      - "005 Optional Quotes" : "peps/PYTAGS_PEP_005_optional_quotes.md"
      - "006 Scrum" : "peps/PYTAGS_PEP_006_scrum.md"
      - "007 Solo" : "peps/PYTAGS_PEP_007_solo.md"
      - "008 Open Source" :  "peps/PYTAGS_PEP_008_oss.md"
  - "FAQ": "FAQ.md"
  - "Glossary": "glossary.md"
  - "Prior Art":
      - "Code Tags": "PRIOR_ART.md"
      - "TODO Objects": "PRIOR_ART_TODO_OBJECTS.md"
  - "Change Log": "CHANGELOG.md"
  - "Contributing": "CONTRIBUTING.md"

validation:
  nav:
    omitted_files: warn
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

plugins:
  - search
  - mkdocstrings