site_name: "pycodetags"
site_url: "https://pycodetags.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of pycodetags, a tool for TODO comments in source code"

repo_url: "https://github.com/matthewdeanmartin/pycodetags"

theme:
  name: material
  features:
    - navigation.footer

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - "Overview": "index.md"
  - "Installation": "installation.md"
  - "Usage":
      - "Usage": "usage.md"
      - "JSON format": "json.md"
      - "Continuous integration": "continuous-integration.md"
      - "Background": "background.md"
  # - "API": "api.md"
  - "Plugin Directory": "plugin_list.md"
  - "Prior Art": "PRIOR_ART.md"
  - "Changes": "../CHANGELOG.md"
  - "Contributing": "../CONTRIBUTING.md"

validation:
  nav:
    omitted_files: warn