[tox]
envlist = py39, py310, py311, py312, py313, py314, py315
requires = tox>=4.0

[testenv]
deps =
    pytest>=7.4.4
    pytest-cov>=4.1.0
    jinja2
    hypothesis>=6.96.0
setenv =
    COVERAGE_FILE = {envtmpdir}/.coverage
commands =
    python -m pytest tests --cov-report term-missing --cov=pycodetags --cov-fail-under=65
